#!/bin/sh
## prepare-commit-msg

branch=$(git branch | grep "*" | awk '{print $2}' | sed -e 's/\(-[0-9]*\)\(-.*\)*/\1/')
perl -i.bak -ne "s/{branch}/$branch/g; print" "$1"

preCommit=$(git log -1 --pretty=format:"%s")
perl -i.bak -ne "s/{pre-commit}/$preCommit/g; print" "$1"
