#!/bin/sh
## prepare-commit-msg

branch=$(git branch | grep "*" | awk '{print $2}' | sed -e 's/\(-[0-9]*\)\(-.*\)*/\1/')
perl -i.bak -pe "s/{branch}/$branch/g;" "$1"

preCommit=$(git log -n 1 --pretty=format:"%s")
perl -i.bak -pe "s/{pre-commit}/$preCommit/g;" "$1"
